apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  - name: ha
    port: 34560
  - name: query
    port: 34561
  selector:
    app: flink
    component: jobmanager
